package = "pen"
version = "dev-1"

source = {
	url = "git://github.com/santojon/pen.git",
}

description = {
	summary = "An override for lapis framework for only Moonscript applications",
	homepage = "...",
	maintainer = "Jonathan Santos <santojon5@gmail.com>",
	license = "MIT",
}

dependencies = {
	"moonscript",
	"lapis",
}

build = {
	type = "builtin",
	modules = {
		["pen"] = "src/lua/pen.lua",
		["pen.app"] = "src/lua/app.lua",
		["pen.application"] = "src/lua/application.lua",
		["pen.cache"] = "src/lua/cache.lua",
		-- ["pen.cmd.actions"] = "src/lua/cmd/actions.lua",
		-- ["pen.cmd.leda"] = "src/lua/cmd/leda.lua",
		-- ["pen.cmd.nginx"] = "src/lua/cmd/nginx.lua",
		-- ["pen.cmd.nginx.attached_server"] = "src/lua/cmd/nginx/attached_server.lua",
		-- ["pen.cmd.nginx.config"] = "src/lua/cmd/nginx/config.lua",
		-- ["pen.cmd.path"] = "src/lua/cmd/path.lua",
		-- ["pen.cmd.templates.app"] = "src/lua/cmd/templates/app.lua",
		-- ["pen.cmd.templates.app_lua"] = "src/lua/cmd/templates/app_lua.lua",
		-- ["pen.cmd.templates.config"] = "src/lua/cmd/templates/config.lua",
		-- ["pen.cmd.templates.config_etlua"] = "src/lua/cmd/templates/config_etlua.lua",
		-- ["pen.cmd.templates.gitignore"] = "src/lua/cmd/templates/gitignore.lua",
		-- ["pen.cmd.templates.mime_types"] = "src/lua/cmd/templates/mime_types.lua",
		-- ["pen.cmd.templates.model"] = "src/lua/cmd/templates/model.lua",
		-- ["pen.cmd.templates.models"] = "src/lua/cmd/templates/models.lua",
		-- ["pen.cmd.templates.models_lua"] = "src/lua/cmd/templates/models_lua.lua",
		-- ["pen.cmd.templates.spec"] = "src/lua/cmd/templates/spec.lua",
		-- ["pen.cmd.templates.tup"] = "src/lua/cmd/templates/tup.lua",
		-- ["pen.cmd.util"] = "src/lua/cmd/util.lua",
		["pen.config"] = "src/lua/config.lua",
		["pen.csrf"] = "src/lua/csrf.lua",
		["pen.db"] = "src/lua/db.lua",
		["pen.db.base"] = "src/lua/db/base.lua",
		["pen.db.base_model"] = "src/lua/db/base_model.lua",
		["pen.db.migrations"] = "src/lua/db/migrations.lua",
		["pen.db.model"] = "src/lua/db/model.lua",
		["pen.db.model.relations"] = "src/lua/db/model/relations.lua",
		["pen.db.mysql"] = "src/lua/db/mysql.lua",
		["pen.db.mysql.model"] = "src/lua/db/mysql/model.lua",
		["pen.db.mysql.schema"] = "src/lua/db/mysql/schema.lua",
		["pen.db.pagination"] = "src/lua/db/pagination.lua",
		["pen.db.postgres"] = "src/lua/db/postgres.lua",
		["pen.db.postgres.model"] = "src/lua/db/postgres/model.lua",
		["pen.db.postgres.schema"] = "src/lua/db/postgres/schema.lua",
		["pen.db.schema"] = "src/lua/db/schema.lua",
		["pen.environment"] = "src/lua/environment.lua",
		["pen.etlua"] = "src/lua/etlua.lua",
		["pen.features.etlua"] = "src/lua/features/etlua.lua",
		["pen.flow"] = "src/lua/flow.lua",
		["pen.html"] = "src/lua/html.lua",
		["pen.http"] = "src/lua/http.lua",
		["pen.lapis.version"] = "src/lua/lapisv.lua",
		-- ["pen.leda"] = "src/lua/leda.lua",
		-- ["pen.leda.files"] = "src/lua/leda/files.lua",
		-- ["pen.logging"] = "src/lua/logging.lua",
		-- ["pen.lua"] = "src/lua/lua.lua",
		-- ["pen.nginx"] = "src/lua/nginx.lua",
		-- ["pen.nginx.context"] = "src/lua/nginx/context.lua",
		-- ["pen.nginx.http"] = "src/lua/nginx/http.lua",
		-- ["pen.nginx.postgres"] = "src/lua/nginx/postgres.lua",
		["pen.request"] = "src/lua/request.lua",
		["pen.router"] = "src/lua/router.lua",
		["pen.server"] = "src/lua/server.lua",
		["pen.session"] = "src/lua/session.lua",
		-- ["pen.spec"] = "src/lua/spec.lua",
		-- ["pen.spec.db"] = "src/lua/spec/db.lua",
		-- ["pen.spec.request"] = "src/lua/spec/request.lua",
		-- ["pen.spec.server"] = "src/lua/spec/server.lua",
		-- ["pen.spec.shared"] = "src/lua/spec/shared.lua",
		-- ["pen.spec.stack"] = "src/lua/spec/stack.lua",
		["pen.util"] = "src/lua/util.lua",
		["pen.util.encoding"] = "src/lua/util/encoding.lua",
		["pen.util.functions"] = "src/lua/util/functions.lua",
		["pen.validate"] = "src/lua/validate.lua",
		["pen.version"] = "src/lua/version.lua",
		["pen.views.error"] = "src/lua/views/error.lua",
		["pen.views.layout"] = "src/lua/views/layout.lua",
	},
	install = {
		bin = {
			"bin/configure",
		}
	},
}